import {auth,googleProvider,signInWithPopup,RecaptchaVerifier,signInWithPhoneNumber,onAuthStateChanged,signOut} from './firebase.js';
const API='http://localhost:8000';let S={movie:null,theatre:null,show:null,seats:[],expires:null,timer:null,userId:null};
const movies=[['Skyline Protocol','Action, Thriller',8.4,'Hindi','https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=700&q=80'],['Midnight Café','Drama, Romance',8.1,'Hindi','https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=700&q=80'],['Orbit 9','Sci-Fi, Adventure',8.7,'English','https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=700&q=80'],['Laughing Matters','Comedy',7.6,'Hindi','https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=80'],['The Last Signal','Horror, Thriller',7.9,'Hindi','https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=80'],['Courtyard Stories','Family, Drama',8,'Hindi','https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=700&q=80']];
const theatres=['PVR Cinemas - World Trade Park','INOX - GT Central','Cinepolis - Triton Mega Mall','Raj Mandir Cinema'];
function render(list=movies){grid.innerHTML=list.map((m,i)=>`<article class="movie" onclick="openBook(${i})"><img src="${m[4]}"><div class="movie-info"><b>${m[0]}</b><div class="meta">${m[1]} • ${m[3]}</div><div>★ ${m[2]}</div></div></article>`).join('')}
function openBook(i){S.movie=movies[i];book.classList.remove('hidden');pay.classList.add('hidden');done.classList.add('hidden');bookTitle.textContent='Book '+S.movie[0];theatres.innerHTML=theatres.map((t,j)=>`<div class="item" onclick="selectTheatre(${j})"><b>${t}</b><div class="meta">${['Malviya Nagar','JLN Marg','Jhotwara','C-Scheme'][j]}, Jaipur</div></div>`).join('');window.scrollTo({top:book.offsetTop-70,behavior:'smooth'})}
function selectTheatre(i){S.theatre=theatres[i];shows.innerHTML=['10:15','13:30','16:45','19:30','22:15'].map((t,j)=>`<div class="item" onclick="selectShow('${t}')"><b>${t}</b><div class="meta">${['2D','2D','3D','IMAX','2D'][j]} • ${S.movie[3]} • ₹${j%2?220:180} • ${36-j*5} seats</div></div>`).join('')}
function selectShow(time){S.show={time};S.seats=[];for(const r of 'ABCDEF')for(let n=1;n<=10;n++){const idx=S.seats.length;S.seats.push({id:idx+1,num:r+n,type:r<'C'?'Standard':r<'E'?'Premium':'Recliner',price:r<'C'?180:r<'E'?260:360,sold:[2,8,19,35,43,58].includes(idx+1),selected:false})}seats.innerHTML=S.seats.map(s=>`<button class="seat ${s.sold?'sold':''}" ${s.sold?'disabled':''} onclick="toggle(${s.id})" id="s${s.id}">${s.num}</button>`).join('');update()}
function toggle(id){const s=S.seats.find(x=>x.id===id);s.selected=!s.selected;document.querySelector('#s'+id).classList.toggle('selected',s.selected);update()}
function chosen(){return S.seats.filter(s=>s.selected)}
function update(){total.textContent='₹'+chosen().reduce((a,s)=>a+s.price,0)}
function checkout(){if(!chosen().length)return alert('Select at least one seat.');S.expires=Date.now()+300000;summary.innerHTML=`<p><b>${S.movie[0]}</b><br>${S.theatre}<br>Today • ${S.show.time}<br>Seats: ${chosen().map(s=>s.num).join(', ')}<br><b>Total: ₹${chosen().reduce((a,s)=>a+s.price,0)}</b></p>`;pay.classList.remove('hidden');book.classList.add('hidden');clearInterval(S.timer);S.timer=setInterval(()=>{const left=Math.max(0,S.expires-Date.now());clock.textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.floor(left/1000)%60).padStart(2,'0')}`;if(!left){clearInterval(S.timer);alert('Reservation expired.');hidePay();openBook(movies.indexOf(S.movie))}},250)}
function confirmPay(){clearInterval(S.timer);const id='BTS-'+Math.floor(100000+Math.random()*900000);details.innerHTML=`<p><b>Booking ID:</b> ${id}</p><p>${S.movie[0]} • ${S.theatre} • ${S.show.time}</p><p>Seats: ${chosen().map(s=>s.num).join(', ')} • ₹${chosen().reduce((a,s)=>a+s.price,0)}</p>`;qr.innerHTML=`<img width="190" src="https://api.qrserver.com/v1/create-qr-code/?size=190x190&data=${encodeURIComponent(id)}">`;pay.classList.add('hidden');done.classList.remove('hidden');window.scrollTo({top:done.offsetTop-70,behavior:'smooth'})}
function hideAll(){book.classList.add('hidden')}function hidePay(){clearInterval(S.timer);pay.classList.add('hidden');book.classList.remove('hidden')}function print(){window.print()}
search.oninput=e=>render(movies.filter(m=>(m[0]+' '+m[1]).toLowerCase().includes(e.target.value.toLowerCase())));document.querySelectorAll('.pill').forEach(b=>b.onclick=()=>{document.querySelectorAll('.pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.g==='all'?movies:movies.filter(m=>m[1].toLowerCase().includes(b.dataset.g.toLowerCase())))});let confirmationResult=null;let recaptcha=null;async function syncUser(user){if(!user){S.userId=null;userLabel.textContent='';signin.textContent='Sign in';return}try{const r=await fetch(API+'/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firebase_uid:user.uid,email:user.email||null,phone_number:user.phoneNumber||null})});if(r.ok)S.userId=(await r.json()).user_id}catch(e){console.warn('Backend auth sync unavailable',e)}if(!S.userId)S.userId=1;userLabel.textContent=user.displayName||user.email||user.phoneNumber||'Signed in';signin.textContent='Sign out'}function openAuth(){authModal.classList.remove('hidden');authError.textContent=''}function closeAuth(){authModal.classList.add('hidden')}signin.onclick=async()=>{if(auth.currentUser){await signOut(auth)}else openAuth()};googleBtn.onclick=async()=>{try{await signInWithPopup(auth,googleProvider);closeAuth()}catch(e){authError.textContent=e.message}};phoneBtn.onclick=async()=>{try{if(!recaptcha)recaptcha=new RecaptchaVerifier(auth,'recaptcha-container',{size:'invisible'});confirmationResult=await signInWithPhoneNumber(auth,phoneInput.value.trim(),recaptcha);otpArea.classList.remove('hidden');phoneBtn.classList.add('hidden')}catch(e){authError.textContent=e.message}};verifyBtn.onclick=async()=>{try{await confirmationResult.confirm(otpInput.value.trim());closeAuth()}catch(e){authError.textContent='Invalid OTP. Please try again.'}};onAuthStateChanged(auth,syncUser);window.openBook=openBook;window.selectTheatre=selectTheatre;window.selectShow=selectShow;window.toggle=toggle;window.checkout=checkout;window.confirmPay=confirmPay;window.hideAll=hideAll;window.hidePay=hidePay;window.print=print;window.closeAuth=closeAuth;render();