-- BookMySeat / BookTheSeat.com Supabase PostgreSQL schema

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE,
  phone_number TEXT UNIQUE,
  firebase_uid TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS movies (
  movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  genre TEXT NOT NULL,
  rating NUMERIC(3,1) DEFAULT 0,
  description TEXT NOT NULL,
  "cast" TEXT DEFAULT '',
  duration INTEGER NOT NULL,
  language TEXT NOT NULL,
  poster_url TEXT NOT NULL,
  release_date DATE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS theatres (
  theatre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  city TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS showtimes (
  showtime_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id BIGINT REFERENCES movies(movie_id) ON DELETE CASCADE,
  theatre_id BIGINT REFERENCES theatres(theatre_id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  format TEXT NOT NULL,
  language TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seats (
  seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showtime_id BIGINT REFERENCES showtimes(showtime_id) ON DELETE CASCADE,
  seat_number TEXT NOT NULL,
  row_letter TEXT NOT NULL,
  seat_type TEXT NOT NULL,
  price NUMERIC(8,2) NOT NULL,
  is_booked BOOLEAN DEFAULT false,
  booked_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(showtime_id, seat_number)
);

CREATE TABLE IF NOT EXISTS bookings (
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(user_id),
  showtime_id BIGINT REFERENCES showtimes(showtime_id),
  total_price NUMERIC(10,2) NOT NULL,
  booking_status TEXT NOT NULL DEFAULT 'pending',
  booking_time TIMESTAMPTZ,
  payment_expiry TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS booking_seats (
  booking_id BIGINT REFERENCES bookings(booking_id) ON DELETE CASCADE,
  seat_id BIGINT REFERENCES seats(seat_id) ON DELETE CASCADE,
  PRIMARY KEY(booking_id, seat_id)
);

CREATE TABLE IF NOT EXISTS seat_reservations (
  reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(user_id),
  showtime_id BIGINT REFERENCES showtimes(showtime_id) ON DELETE CASCADE,
  seat_id BIGINT REFERENCES seats(seat_id) ON DELETE CASCADE,
  reservation_expiry TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(showtime_id, seat_id)
);

CREATE INDEX IF NOT EXISTS ix_reservation_expiry ON seat_reservations(reservation_expiry);
CREATE INDEX IF NOT EXISTS ix_showtimes_movie_theatre_date ON showtimes(movie_id, theatre_id, date);
CREATE INDEX IF NOT EXISTS ix_bookings_user ON bookings(user_id);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE theatres ENABLE ROW LEVEL SECURITY;
ALTER TABLE showtimes ENABLE ROW LEVEL SECURITY;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE seat_reservations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read movies" ON movies FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public read theatres" ON theatres FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public read showtimes" ON showtimes FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "public read seats" ON seats FOR SELECT TO anon, authenticated USING (true);
